export enum EAUTH_ERROR {
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN_OR_EXPIRED = 'INVALID_TOKEN_OR_EXPIRED',
}

export enum EAPI_USER_ERROR {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_IN_USED = 'EMAIL_ALREADY_IN_USED',
  NO_RESULT = 'NO_RESULT',
}

export enum EAPI_SEARCH_ERROR {
  NOT_FOUND = 'NOT_FOUND',
  NO_RESULT = 'NO_RESULT',
}
